### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by ValZapod** [reubenhwk/radvd#109]
https://github.com/reubenhwk/radvd/blob/f9ac9a88775225eddf39208eefbc136a23757690/send.c#L789-L794

Why do you need this? Line 792 can be fully deleted.

https://github.com/reubenhwk/radvd/blob/f9ac9a88775225eddf39208eefbc136a23757690/send.c#L161
https://github.com/reubenhwk/radvd/blob/f9ac9a88775225eddf39208eefbc136a23757690/send.c#L331
Twice parentheses

https://github.com/reubenhwk/radvd/blob/f9ac9a88775225eddf39208eefbc136a23757690/process.c#L378-L385

My analyzer says that suffix[0] == '\0' is always true... And there https://github.com/reubenhwk/radvd/blob/f9ac9a88775225eddf39208eefbc136a23757690/process.c#L408 always false

Also this one is always true 
https://github.com/reubenhwk/radvd/blob/f9ac9a88775225eddf39208eefbc136a23757690/radvd.c#L403
and this one https://github.com/reubenhwk/radvd/blob/f9ac9a88775225eddf39208eefbc136a23757690/radvd.c#L593
is always false

**Comment by reubenhwk** [comment]
Can you make a pull request for everything but the suffix stuff?  I dunno
if I want to trust your analyzer to those changes.  That code's been
working for 9 years.

**Comment by ValZapod** [comment]
@reubenhwk Unfortunately, I do not have access to computer now)) And android is not comfortable for this.

**Comment by reubenhwk** [comment]
Does that mean your code analysis tool is Chrome?

**Comment by ValZapod** [comment]
Very funny. Chrome cannot analyze C code, obviously.

**Comment by ValZapod** [comment]
Besides that radvd does not have any issues, not like in iputils, anyway. https://github.com/iputils/iputils/issues/205
So I am closing this.

**Comment by reubenhwk** [comment]
I’ll make the other cleanups you suggested when I get a chance unless somebody else beats me to it.

**Comment by ValZapod** [comment]
@reubenhwk What can you say about https://github.com/reubenhwk/radvd/blob/849f69c3e6876fad009a8f3be27d7533ce9a56db/process.c#L400
It says that label_len >= (INT_MAX - 1) is always false. I suppose because it is `int label_len = char nd_opt_dnssli_suffixes[]`, so it is impossible.

And this one
https://github.com/reubenhwk/radvd/blob/dec440273f4769e6daf1814bd2622a3efd683541/process.c#L77
It is also always false, though in this case I cannot understand why))
