### ISSUE TITLE
How to advertise 2 prefixes on an interface?

### ISSUE THREAD

**Issue by ipilcher** [reubenhwk/radvd#114]
I am trying to configure radvd to advertise 2 prefixes on an interface - an internal ULA prefix and a **dynamic** prefix delegated by my ISP.

My configuration file looks like this:

```
interface br253
{
        AdvSendAdvert on;
        MinRtrAdvInterval 30;
        MaxRtrAdvInterval 100;
        AdvDefaultLifetime 1800;
        AdvOtherConfigFlag on;

        prefix 2605:6000:8c82:1efd:0000:0000:0000:0000/64
        {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr off;
        };

        prefix fd00:dcaf:bad:fd::/64
        {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr off;
        };

        RDNSS fd00:dcaf:bad:fd::fffe
        {
                AdvRDNSSLifetime 150;
        };

        DNSSL penurio.us
        {
                AdvDNSSLLifetime 150;
        };
};
```

But only the delegated prefix is being advertised.  (Verified with tcpdump/wireshark.)

What do I have to do to advertise **both** prefixes?

**Comment by reubenhwk** [comment]
Not sure. It should advertise both. What does the log say?

**Comment by ipilcher** [comment]
Aaaaand ... I can no longer duplicate the issue.  radvd is advertising both prefixes with the config file above.

Sorry for the noise!

**Comment by reubenhwk** [comment]
Glad I could help! :D
