### ISSUE TITLE
There is no "configure" file

### ISSUE THREAD

**Issue by yugun** [reubenhwk/radvd#123]
I'm trying to build radvd-master, but there is no "configure" file.

Should I create "configure" file with autotools and "configure.ac"?

**Comment by reubenhwk** [comment]
Run autogen.sh

**Comment by stappersg** [comment]
Yes,  `./autogen.sh`  generates the `configure` script.


@yugun  please confirm

**Comment by stappersg** [comment]
@Neustradamus  please has a close look at the time stamps of the entries in this issue.
