### ISSUE TITLE
Router Advertisement being received by the wrong interface

### ISSUE THREAD

**Issue by miguelxpn** [reubenhwk/radvd#47]
Hello. I have the following radvd.conf file:

```
interface eth0
{
        AdvSendAdvert on;
        MinRtrAdvInterval 30;
        MaxRtrAdvInterval 100;
        route 2000:e000:0:2::/64
        {
                AdvRoutePreference low;
        };
};

interface tap_tap
{
        AdvSendAdvert on;
        MinRtrAdvInterval 30;
        MaxRtrAdvInterval 100;
        prefix 2000:e000:0:2::/64
        {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };

        route 2000:e000:0:1::/64
        {
                AdvRouteLifetime infinity;
                AdvRoutePreference high;
        };

};
```

The idea is to have a eth0 interface facing an internal network and a tap interface which will have people connected from VPNs. On the eth0 interface I want to advertise routes so everyone in the internal network can see the VPN clients, the problem is that the eth0 advertisement gets picked up by other interfaces such as eth1 and that messes up the whole routing:

```
# radvd configuration generated by radvdump 1.9.2
# based on Router Advertisement from fe80::b076:c0ff:fe83:d38a
# received by interface eth1
#

interface eth1
{
        AdvSendAdvert on;
        # Note: {Min,Max}RtrAdvInterval cannot be obtained with radvdump
        AdvManagedFlag off;
        AdvOtherConfigFlag off;
        AdvReachableTime 0;
        AdvRetransTimer 0;
        AdvCurHopLimit 64;
        AdvDefaultLifetime 300;
        AdvHomeAgentFlag off;
        AdvDefaultPreference medium;
        AdvSourceLLAddress on;

        route 2000:e000:0:2::/64
        {
                AdvRoutePreference low;
                AdvRouteLifetime 300;
        }; # End of route definition

}; # End of interface definition
#
# radvd configuration generated by radvdump 1.9.2
# based on Router Advertisement from fe80::b076:c0ff:fe83:d38a
# received by interface eth0
#

interface eth0
{
        AdvSendAdvert on;
        # Note: {Min,Max}RtrAdvInterval cannot be obtained with radvdump
        AdvManagedFlag off;
        AdvOtherConfigFlag off;
        AdvReachableTime 0;
        AdvRetransTimer 0;
        AdvCurHopLimit 64;
        AdvDefaultLifetime 300;
        AdvHomeAgentFlag off;
        AdvDefaultPreference medium;
        AdvSourceLLAddress on;

        route 2000:e000:0:2::/64
        {
                AdvRoutePreference low;
                AdvRouteLifetime 300;
        }; # End of route definition

}; # End of interface definition
```

The weird thing is that I've succesfully used this exact same setup in some environments, for some reason in some environments this happens out of nowhere, is there anything that I'm missing?

Thank you!

**Comment by reubenhwk** [comment]
Is radvd running on the system doing the routing?  Try disabling
autoconfiguration on your router.

Auto configuration can be disabled temporary for eth1 with:

sudo sysctl -w net.ipv6.conf.eth1.autoconf=0
sudo sysctl -w net.ipv6.conf.eth1.accept_ra=0

or for all interfaces with:

sudo sysctl -w net.ipv6.conf.all.autoconf=0
sudo sysctl -w net.ipv6.conf.all.accept_ra=0

**Comment by miguelxpn** [comment]
Yes! The system doing the routing is running radvd, 

I tried disabling the auto configuration for eth1 and indeed that made it so the RA is ignored and the routing works, however I still don't understand why the RA was being picked up by eth1 in the first place.

Thank you again.

**Comment by reubenhwk** [comment]
I don't either.  Can you post the logs?

**Comment by miguelxpn** [comment]
Sure, here they are:

https://gist.github.com/miguelxpn/046d7e893b2870ddc162

**Comment by reubenhwk** [comment]
The lines in the log...

"received packet from unknown interface: 3"

...is almost definitely eth1.  Radvd says "unknown" because eth1 isn't in
the config file (logging could be improved to get the name when it's
unknown using if_indextoname).

The data structure that if_index, 3, comes from is recvmsg in recv_rs_ra.
That's a systemcall, so the OS really does think that eth1 is getting an RA.

I'm noticing that you're getting RA from two different addresses...

received RA from fe80::2ac:48ff:fec5:21bb
received RA from fe80::b076:c0ff:fe83:d38a

Can you confirm that there is no other radvd running on your network?  You
can use radvdump...

**Comment by miguelxpn** [comment]
There were was another radvd running on the network but it's advertising a completely different prefix that doesn't affect the one I was trying to set up, curiously enough the same thing happened to that RA, it also was received by both interfaces. 

Sadly I don't have access to that environment any more so I can't do more experimenting on it, I'll close this as disabling the auto configuration on the interface that shouldn't receive is an acceptable workaround in this case.

Thank you for the help!
