### ISSUE TITLE
why does ABRO option have a prefix length?

### ISSUE THREAD

**Issue by mcr** [reubenhwk/radvd#49]
At the ETSI (IETF94-colocated) plugfest, I was  trying to get ABROs emitted at the 6lo plugfest that can be consumed by RIOT-OS. (which we were able to do).  It worked, btw.
                                     
The config I was using looked like:

    abro fe80::216:3ead:fd4:1165/64 {                                          
          AdvVersionLow 10;                                                    
          AdvVersionHigh 2;                                                    
          AdvValidLifeTime 2;                                                  
    };                                                                         

                                                                           
The IP address part is copied into the ABRO block, but what's the / prefix-length part about? I don't think it belongs at all.  I suggest modifying the grammar not to require it.

**Comment by reubenhwk** [comment]
Hmmmm...  After digging into the code and the RFC a bit, looks like the
prefix-length isn't really needed there.  The ABRO option is just a single
IPv6 address right?

I think it would be a fairly simple change, but we can't break backward
compatibility with existing configurations..

In gram.y, this line would have to be updated to include a 2nd rule
somehow...

abrohead : T_ABRO IPV6ADDR '/' NUMBER

Maybe

abrohead : abroaddr

abroaddr : T_ABRO IPV6ADDR | T_ABRO IPV6ADDR '/' NUMBER

**Comment by reubenhwk** [comment]
I pushed a change to the master branch which deprecates the prefix length on ABRO.  Please give it a try and let me know if it's working as you expect.
