### ISSUE TITLE
process.c:373: bad way to test for overflow ?

### ISSUE THREAD

**Issue by dcb314** [reubenhwk/radvd#52]
[process.c:373]: (warning) Invalid test for overflow 'label_len>label_len+2'. Condition is always false unless there is overflow, and overflow is Undefined Behaviour.

Source code is

 label_len > label_len + 2

Suggest cast out to larger integer type, then compare.

**Comment by reubenhwk** [comment]
<pre>
-                                           label_len > label_len + 2
+                                           label_len >= (INT_MAX-1)
</pre>

Is this better?  Please check the math.  I'll commit this in the next day or so if I don't hear back from you.
