### ISSUE TITLE
Include a systemd service

### ISSUE THREAD

**Issue by candrews** [reubenhwk/radvd#56]
Can radvd please include and (optionally) install a systemd service?

Many distros are using systemd (such as Debian, Ubuntu, and Fedora) and others are supporting but not necessarily using it by default (Gentoo). Currently, each one of these distributions has to create and distribute their own systemd service for radvd, even though they're all (virtually) identical, with the only differences being inadvertent or unnecessary. One of the goals of systemd is ["to unify the boot and service management between distributions with systemd."](http://0pointer.de/blog/projects/systemd-update.html) I think everyone agrees that it's bad if every distribution patched the radvd source... so this situation is also less than ideal. Besides making life easier for distributions and users, upstreaming a systemd service also helps radvd out in another way - it makes things more consistent, which eases maintainability.

Here's the systemd unit I propose, using what's in [Gentoo](https://github.com/gentoo/gentoo/blob/fed779d199e5f0718550194518d85a1567c55767/net-misc/radvd/files/radvd.service) and [Fedora](http://pkgs.fedoraproject.org/cgit/rpms/radvd.git/tree/radvd.service) as a baseline:
```
[Unit]
Description=Router advertisement daemon for IPv6
Documentation=man:radvd(8)
After=network.target

[Service]
User=radvd
Group=radvd
Type=forking
ExecStartPre=/usr/sbin/radvd --configtest
ExecStart=/usr/sbin/radvd --logmethod stderr --debug 0
ExecReload=/usr/sbin/radvd --configtest ; \
           /bin/kill -HUP $MAINPID
CPUSchedulingPolicy=idle
PIDFile=/run/radvd/radvd.pid
RuntimeDirectory=radvd
CapabilityBoundingSet=CAP_NET_BIND_SERVICE  CAP_NET_RAW
AmbientCapabilities=CAP_NET_BIND_SERVICE  CAP_NET_RAW
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=full
ProtectHome=yes
NoNewPrivileges=yes

[Install]
WantedBy=multi-user.target
```

The de facto way to handle systemd unit is with the flags `--without-systemduserunitdir` (which doesn't install the unit) and `--with-systemduserunitdir=[path]` (which installs the unit to the given path).

**Comment by reubenhwk** [comment]
Yes!  I've been wanting to do this for a while.  This info is going to make
it easier.  Thanks!

Expect radvd 2.14 to have this in the next week or so.

**Comment by reubenhwk** [comment]
question,

Wouldn't ExecReload do better like this...

ExecReload=/usr/sbin/radvd --configtest && /bin/kill -HUP $MAINPID

**Comment by candrews** [comment]
Wow, yeah. That does seem better!

**Comment by reubenhwk** [comment]
Another question...

who uses --with-systemduserunitdir?  Is there a standard m4 macro for this
yet?

**Comment by reubenhwk** [comment]
Nevermind...  I think I found the useful info here...

https://www.freedesktop.org/software/systemd/man/daemon.html

**Comment by reubenhwk** [comment]
Hi Craig,

Can you checkout the radvd/systemd branch and give it a go?  Let me know if
the changes work.

Thanks in advance,
Reuben

**Comment by candrews** [comment]
https://github.com/reubenhwk/radvd/blob/87e35be85ef56e28a59b68bd01ec8eaa96acbfef/radvd.service.in is missing the hardening features - perhaps those could be added in? I submitted a PR to your branch: 
https://github.com/reubenhwk/radvd/pull/58

**Comment by candrews** [comment]
Distros (including Gentoo and Fedora) run radvd as the "radvd" user (which is nice as it reduces the privileges more) - would it make sense to add "--username radvd" to ExecStart and add "CAP_SETUID CAP_SETGID" to the CapabilityBoundingSet?

I think that may mean the readme and/or installation instructions... But it would be nice as then distros could use the upstream service unmodified.

**Comment by reubenhwk** [comment]
Not sure it's necessary. RADVD forks off a unprivileged process to do all the work which runs as nobody. The privileged process still runs as root. Is it worth the effort?  Should both processes run as the runas user, or just the privileged one?

**Comment by reubenhwk** [comment]
systemd service file is now included
