### ISSUE TITLE
trouble starting radvd via ssh

### ISSUE THREAD

**Issue by nachtgeist** [reubenhwk/radvd#71]
Hi Reuben,

originally I noticed this problem when I wanted to do `ssh router service radvd restart` after I had upgraded the router to Debian stretch, which ships radvd v2.15: the ssh connection wouldn't close, and just sit there forever. I was able to reproduce this behavior without any scripts involved by directly running what the init script would eventually call: `ssh router radvd -u radvd -p /var/run/radvd/radvd.pid`

This worked fine on jessie (v1.9-something).

git-bisect'ing revealed the culprit as 5294e6fc0cc033a8dde64d51eefdc4c1f80e4244. Before that commit, radvd would fork and let the ssh connection terminate properly...

Cheers
Daniel

**Comment by nachtgeist** [comment]
I found out that something goes wrong with the stdout FD;
These commands behave as expected and ssh returns after radvd daemon()'s to background:

`ssh router radvd -u radvd -p /var/run/radvd/radvd.pid >/dev/null`
`ssh router radvd -u radvd -p /var/run/radvd/radvd.pid -d3`

**Comment by reubenhwk** [comment]
I think there's actually a bug in log.c where the default log method,
STDERR_SYSLOG, is comparing the log level to the wrong value.  I dont like
how STDERR is the default, and so is daemonize.  Any code that daemonizes
should close stdin, stdout, and stderr, but STDERR_SYSLOG prevents that.

It looks like you're trying to SSH to a host and start radvd.  If that is
what you're doing, you should set the log method to logfile, and give it a
log file path, or set the log method to syslog.

ssh router radvd -u radvd -p /var/run/radvd/radvd.pid -m logfile -l
/var/log/radvd.log

**Comment by nachtgeist** [comment]
Ah, thanks for your input. Your workaround works.

What do you think of
- setting the default log method to `SYSLOG` and
- setting it to `STDERR_SYSLOG` within the 'n'-branch of the getopt switch **if** log_method wasn't set in a previous iteration of the getopt-while-loop?

**Comment by robbat2** [comment]
@nachtgeist I've wondered about refactoring the logmethod, to select zero or more of the log destinations and maybe that makes sense for this. If daemonize is set, then stderr/stdout should be dropped from the destinations.
