### ISSUE TITLE
What causes Windows "route limit" to be reached?

### ISSUE THREAD

**Issue by pimzand** [reubenhwk/radvd#75]
After years and years of smooth operation, suddenly, after an upgrade of Fedora 25 to Fedora 26, we started getting serious issues with IPv6 auto configuration. See my [bugzilla report](https://bugzilla.redhat.com/show_bug.cgi?id=1475432).

Note that both Fedora 25 and Fedora 26 ship radvd 2.14.

The issue is that all our Windows hosts that use IPv6 autoconfiguration lose their default gateway after a while, usually within 24 hours. An error is recorded in the Windows System event log, Event 4205, source "tcpip", message:

"_Autoconfigured route limit has been reached. No further autoconfigured routes will be added until the interface is reconnected_".

Indeed, a short disconnect of the (virtual) ethernet cable will make the default route return. For a while. So will a reboot.

Windows forums aren't very helpful in solving this issue. The best answer they can think of is [try to disable IPv6](https://social.technet.microsoft.com/forums/en-us/56315716-c41d-4d5f-b512-8d0970dd74da/autoconfigured-address-limit-has-been-reached-no-further-autoconfigured-addresses-will-be-added), Oh well.

On Bugzilla I wrote the problem went away after a while. It did, but somehow it returned after a power surge, where the Fedora box needed rebooting several times. It led me to believe that restarting radvd might be the issue here, rather than version upgrading.

I built an RPM using radvd 2.17 which I am running now, and the issue is still there.

On top of that, I noticed that Windows hosts using autoconfiguration are experiencing packet loss when pinged from outside the subnet. Manual IPv6 configuration fixes that.

Linux hosts in the same test are not losing packets regardless of configuration method.

I checked for rogue RA's. They don't appear to be there,

I tried all sorts of configurations. Currently it is like this.
Perhaps I should advertise an explicit route to ::/0 ?

```
# main network
interface enp31s0f0
{
        AdvSendAdvert on;
        AdvDefaultPreference high;
        AdvDefaultLifetime 3600;
        MaxRtrAdvInterval 60;
        prefix xxxx:yyyy:zzzz:fff0::/64 {};
        RDNSS xxxx:yyyy:zzzz:fff0::1 xxxx:yyyy:zzzz:fff0:221:5eff:fe6b:b9e0 {};
        DNSSL example.nl {};
};
````

**Comment by robbat2** [comment]
How many routes do the Windows systems have? 

Can you capture & provide a snapshot of the Windows IPv6 route table running on Fedora25 vs radvd 2.17?

**Comment by pimzand** [comment]
netsh interface ipv6 show route
```
Publish  Type      Met  Prefix                    Idx  Gateway/Interface Name
-------  --------  ---  ------------------------  ---  ------------------------
No       System    256  ::1/128                     1  Loopback Pseudo-Interface 1
No       Manual    16   2a00:18c8:1001:fff0::/64   19  Intel Ethernet
No       System    256  2a00:18c8:1001:fff0:6a05:caff:fe47:4692/128   19  Intel Ethernet
No       System    256  fe80::/64                  19  Intel Ethernet
No       System    256  fe80::/64                   6  Ethernet 2
No       System    256  fe80::/64                   4  Wi-Fi
No       System    256  fe80::/64                   3  Local Area Connection* 10
No       System    256  fe80::5efe:192.168.10.131/128   18  isatap.macroscoop.nl
No       System    256  fe80::215:afff:fe16:2bb0/128    4  Wi-Fi
No       System    256  fe80::224:8cff:fe7b:5b9f/128    6  Ethernet 2
No       System    256  fe80::2015:afff:fe16:2bb0/128    3  Local Area Connection* 10
No       System    256  fe80::6a05:caff:fe47:4692/128   19  Intel Ethernet
No       System    256  ff00::/8                    1  Loopback Pseudo-Interface 1
No       System    256  ff00::/8                   19  Intel Ethernet
No       System    256  ff00::/8                    6  Ethernet 2
No       System    256  ff00::/8                    4  Wi-Fi
No       System    256  ff00::/8                    3  Local Area Connection* 10
```
netsh interface ipv6 show neighbors
notice the radvd router is marked stale
```
Interface 4: Wi-Fi


Internet Address                              Physical Address   Type
--------------------------------------------  -----------------  -----------
fe80::223:54ff:fe51:a4ca                      00-00-00-00-00-00  Unreachable
fe80::250:56ff:fe9b:7056                      00-00-00-00-00-00  Unreachable
fe80::2e27:d7ff:fe14:87b6                     00-00-00-00-00-00  Unreachable
fe80::3e97:eff:fe25:cfd1                      00-00-00-00-00-00  Unreachable
fe80::e2cb:4eff:fe0e:f6a7                     00-00-00-00-00-00  Unreachable
ff02::16                                      33-33-00-00-00-16  Permanent
ff02::fb                                      33-33-00-00-00-fb  Permanent
ff02::1:2                                     33-33-00-01-00-02  Permanent
ff02::1:ff00:1                                33-33-ff-00-00-01  Permanent
ff05::c                                       33-33-00-00-00-0c  Permanent

Interface 3: Local Area Connection* 10


Internet Address                              Physical Address   Type
--------------------------------------------  -----------------  -----------
fe80::223:54ff:fe51:a4ca                      00-00-00-00-00-00  Unreachable
fe80::250:56ff:fe9b:7056                      00-00-00-00-00-00  Unreachable
fe80::2e27:d7ff:fe14:87b6                     00-00-00-00-00-00  Unreachable
fe80::3e97:eff:fe25:cfd1                      00-00-00-00-00-00  Unreachable
fe80::e2cb:4eff:fe0e:f6a7                     00-00-00-00-00-00  Unreachable
ff02::16                                      33-33-00-00-00-16  Permanent
ff02::fb                                      33-33-00-00-00-fb  Permanent
ff02::1:2                                     33-33-00-01-00-02  Permanent
ff02::1:ff00:1                                33-33-ff-00-00-01  Permanent
ff05::c                                       33-33-00-00-00-0c  Permanent

Interface 19: Intel Ethernet


Internet Address                              Physical Address   Type
--------------------------------------------  -----------------  -----------
2a00:18c8:1001:fff0::1                        90-e2-ba-27-0d-44  Reachable
2a00:18c8:1001:fff0::226                      00-1b-21-70-8b-e7  Stale
2a00:18c8:1001:fff0:218:4dff:fe33:e3b5        00-00-00-00-00-00  Unreachable
2a00:18c8:1001:fff0:21a:64ff:fec1:a730        00-1a-64-c1-a7-30  Stale
2a00:18c8:1001:fff0:21b:21ff:fe70:8be7        00-1b-21-70-8b-e7  Stale
2a00:18c8:1001:fff0:221:5eff:fe6b:b9e0        00-21-5e-6b-b9-e0  Stale
2a00:18c8:1001:fff0:221:5eff:fe6b:b9e4        00-00-00-00-00-00  Unreachable
2a00:18c8:1001:fff0:230:48ff:fe9e:c15f        00-00-00-00-00-00  Unreachable
2a00:18c8:1001:fff0:250:56ff:fe9b:edf         00-50-56-9b-0e-df  Stale
2a00:18c8:1001:fff0:250:56ff:fe9b:13c6        00-50-56-9b-13-c6  Stale
2a00:18c8:1001:fff0:5ef3:fcff:fee1:104d       00-00-00-00-00-00  Unreachable
2a00:18c8:1001:fff0:5ef3:fcff:fee1:1231       00-00-00-00-00-00  Unreachable
2a00:18c8:1001:fff0:5ef3:fcff:fee1:12d9       00-00-00-00-00-00  Unreachable
2a00:18c8:1001:fff0:e61f:13ff:fe28:5561       00-00-00-00-00-00  Unreachable
2a00:18c8:1001:fff0:e61f:13ff:fe2f:562        e4-1f-13-2f-05-62  Reachable
2a00:18c8:1001:fff0:fa0f:41ff:fef3:22bd       00-00-00-00-00-00  Unreachable
fe80::21b:21ff:fe70:8be7                      00-1b-21-70-8b-e7  Stale
fe80::223:54ff:fe51:a4ca                      00-23-54-51-a4-ca  Stale
fe80::250:56ff:fe9b:edf                       00-50-56-9b-0e-df  Stale
fe80::250:56ff:fe9b:7056                      00-50-56-9b-70-56  Stale
fe80::2e27:d7ff:fe14:87b6                     00-00-00-00-00-00  Unreachable
fe80::3e97:eff:fe25:cfd1                      00-00-00-00-00-00  Unreachable
fe80::c067:950e:8135:13b9                     90-e2-ba-27-0d-44  Stale (Router)
fe80::e2cb:4eff:fe0e:f6a7                     00-00-00-00-00-00  Unreachable
ff02::1                                       33-33-00-00-00-01  Permanent
ff02::2                                       33-33-00-00-00-02  Permanent
ff02::c                                       33-33-00-00-00-0c  Permanent
ff02::16                                      33-33-00-00-00-16  Permanent
ff02::fb                                      33-33-00-00-00-fb  Permanent
ff02::1:2                                     33-33-00-01-00-02  Permanent
ff02::1:3                                     33-33-00-01-00-03  Permanent
ff02::1:ff00:1                                33-33-ff-00-00-01  Permanent
ff02::1:ff00:226                              33-33-ff-00-02-26  Permanent
ff02::1:ff2f:562                              33-33-ff-2f-05-62  Permanent
ff02::1:ff35:13b9                             33-33-ff-35-13-b9  Permanent
ff02::1:ff47:4692                             33-33-ff-47-46-92  Permanent
ff02::1:ff51:a4ca                             33-33-ff-51-a4-ca  Permanent
ff02::1:ff6b:b9e0                             33-33-ff-6b-b9-e0  Permanent
ff02::1:ff70:8be7                             33-33-ff-70-8b-e7  Permanent
ff02::1:ff9b:edf                              33-33-ff-9b-0e-df  Permanent
ff02::1:ff9b:7056                             33-33-ff-9b-70-56  Permanent
ff02::1:ffc1:a730                             33-33-ff-c1-a7-30  Permanent
ff05::c                                       33-33-00-00-00-0c  Permanent

Interface 1: Loopback Pseudo-Interface 1


Internet Address                              Physical Address   Type
--------------------------------------------  -----------------  -----------
ff02::c                                                          Permanent
ff02::16                                                         Permanent
ff02::fb                                                         Permanent
ff02::1:2                                                        Permanent
ff02::1:ff00:1                                                   Permanent
ff05::c                                                          Permanent

Interface 6: Ethernet 2


Internet Address                              Physical Address   Type
--------------------------------------------  -----------------  -----------
fe80::223:54ff:fe51:a4ca                      00-00-00-00-00-00  Unreachable
fe80::250:56ff:fe9b:7056                      00-00-00-00-00-00  Unreachable
fe80::2e27:d7ff:fe14:87b6                     00-00-00-00-00-00  Unreachable
fe80::3e97:eff:fe25:cfd1                      00-00-00-00-00-00  Unreachable
fe80::e2cb:4eff:fe0e:f6a7                     00-00-00-00-00-00  Unreachable
ff02::16                                      33-33-00-00-00-16  Permanent
ff02::fb                                      33-33-00-00-00-fb  Permanent
ff02::1:2                                     33-33-00-01-00-02  Permanent
ff02::1:ff00:1                                33-33-ff-00-00-01  Permanent
ff05::c                                       33-33-00-00-00-0c  Permanent
```

**Comment by pimzand** [comment]
I can think of some wild theories that could explain this behaviour:

1) Upon shutdown, radvd sends a special RA. Windows hosts store this RA somewhere persistently. When radvd is running again, every single RA is seen by the Windows host is now interpreted as a new route.

2) We've had a lot of prefix changes in the first half of 2017, due to SixXS freeze and SixXS sunset. We have native IPv6 now. Somewhere, Windows host have stored these prefixes persistently, and now we have hit a limit.

**Comment by pimzand** [comment]
[Microsoft KB2750841](https://support.microsoft.com/en-us/help/2750841/an-ipv6-readiness-update-is-available-for-windows-7-and-for-windows-se) mentions something of a route limit

**Comment by pimzand** [comment]
The packet loss I mentioned earlier appears to be caused by Windows constantly losing and acquiring a default route.

**Comment by robbat2** [comment]
I don't see ANY default route in your `netsh interface ipv6 show route` output. The knowledgebase item you reference says the limit gets raised to 100 routes per interface, you're only at 5 routes. I do wonder if it meant to say addresses rather than routes.

Can you include the output of `netsh interface ipv6 show address`?  When the machine state is fresh, and when the problem starts occurring again. I'm interested to know how many addresses it's picked up over that time. Your comment about the SixXS change adding lots of prefix changes makes me wonder about that: if Windows didn't expire all of those addresses.

I did also see an [interesting comment on ServerFault](https://serverfault.com/questions/273716/how-to-remove-autoconfigured-ipv6-addresses-in-windows-7-2008):
> It turned out that the problems I was seeing stemmed from the fact that the server in question found itself in a new network environment and thus went to "Public" security settings.

As for your theory about special RAs, when radvd shuts down, it DOES send RAs with zero lifetimes, as per the various settings, with defaults in your case: 
- `DeprecatePrefix`(off) 
- `RemoveRoute`(on) Doesn't apply in your case, you don't have any specific route definitions
- `FlushRDNSS`(on)
- `FlushDNSSL`(on)

However, the nature of those RAs, is specifically that they should NOT be cached. Their objective is to REMOVE the prefix/route/rdnss/dnssl entries from hosts in the network.

**Comment by pimzand** [comment]
It's been a while since I commented on this, but it is still a hairpulling issue.

I believe the key issue here is Windows sporadically losing the default gateway
before regaining it after receiving a new advertisement. This happens no matter
what interval I choose.

I believe the final definite loss of the gateway happens when there have been
to many sporadic gateway losses, triggering the "route limit". 

This Powershell script continuously  monitors my IPv6 routes. It will print
a timestamp for every second there is no IPv6 gateway.

`while ($true) {if (netsh interface ipv6 show route | Select-String ::/0 -quiet) {} else {Get-Date}; Start-Sleep -s 1} 
`

I can run it on any Windows machine, virtual or physical, any Windows version and it will always
print timestamps within a couple of minutes, especially on fresh booted hosts.

On my laptop, it will print dates connected wired to this network, and it will not print anything
when wirelessly connected to a Fritz!Box acting as a RA.

**Comment by pimzand** [comment]
Now here's an interesting observation, I just witnessed:

Using Wireshark, I could always see the gateway is regained the moment a RA is received.

But now I see I can actually force a gateway loss by pinging the Windows host
from an outside IPv6 subnet. And what's really interesting: icmpseq=1 always
is successful, then the gateway is lost, causing packet loss, then after 10-20
packets the packets are being returned again, when the Windows host receives
the next RA.

Maybe this explains this is never happening on the Fritz!Box network, because
that does not forward inward IPv6 traffic.

**Comment by reubenhwk** [comment]
Is this a bug in Windows which causes it to loose connectivity over IPv6
which can be triggered remotely?  If so that's really bad news and we need
to inform Microsoft privately so they can issue a patch.

**Comment by pimzand** [comment]
Well it can be triggered remotely, if the external firewall allows to forward icmpv6 to the Windows host.
It happens even with the Windows Firewall active.
I could reproduce this on a fresh Windows 2012 R2 install, no Windows Update,
nothing installed except VMware Tools.

What's puzzling me now is
- why did I not see this before I upgraded to Fedora 26
- why is't anyone else seeing this

**Comment by reubenhwk** [comment]
What were you using before fedora 26. Can you try whatever that was again?  Maybe 26 is a red herring.

**Comment by pimzand** [comment]
I've been using Fedora from the start and Red Hat Linux (non-Enterprise) before that.
I've been using IPv6 on it since at least 2003, maybe earlier.
After having upgraded tot Fedora 26, I downgraded  radvd to that of Fedora 25, and booted a F25
kernel. It did not help. Recently, I upgraded to Fedora 27 which comes with radvd 2.17 natively.

I'm still not sure whether this is related to changes in Fedora or not.

**Comment by pimzand** [comment]
Using Wireshark on the router, and continuously pinging the Windows host from an external address,
I'm seeing the gateway is lost _every_ time
- from the moment the Windows host does a Neighbor Solicitation for the router's address
- until the moment the Windows host receives a Router Advertisement

The Neighbor Solicitations _are_ being answered.

**Comment by pimzand** [comment]
I think I'm getting closer.

The Neighbor Advertisements that the router sends, have the solicited flag on, but the router flag is off.
Shouldn't the router flag be on?
What controls that?

**Comment by pimzand** [comment]
Found it! It did have to do with the Fedora upgrade, something had changed in sysctl processing.
/etc/sysctl.conf and /etc/sysctl.d/*.conf are being processed too early.

`net.ipv6.conf.all.forwarding = 1`
and
`net.ipv6.conf.default.forwarding = 1`
but
`net.ipv6.conf.<myinterface>.forwarding = 0`

Running `systemctl --system` manually fixes it.

Apparently, the unfixed sysctl settings did allow ipv6 forwarding, but caused the interfaces to act as
non-routers, utterly confusing Windows hosts.

**Comment by reubenhwk** [comment]
Interesting!  Can you explain what effect this has on the packets RADVD is
sending out?  I have to admit, I still don't understand the problem.

**Comment by pimzand** [comment]
It is not a radvd issue.
It was radvd tellling the router is a router, and the kernel telling the router is not a router.
radvd controls router advertisements, and sysctl controls neighbor advertisements.

Apparently systemd is applying /etc/sysctl.d/*.conf files before the network interfaces are set up.

**Comment by pimzand** [comment]
systemd-sysctl.service is applying /etc/sysctl.conf, /etc/sysctl.d/*.conf and /usr/lib/sysctl.d/*.conf
just after modules have been loaded. Too early to enable IPv6 forwarding, because forwarding
has to be enabled on every interface individually, rather than just once for IPv4.

I created a systemd unit file that runs the service again just after network online,
(two seconds later) and now everything works just fine, after having rebooted
every WIndows host in the network as well.

I suppose others aren't seeing this because I'm not running firewalld, just plain
old iptables. I suppose firewalld would take care of this.

This was never a radvd issue, so I'm closing it now.
