### ISSUE TITLE
Losing default route on Android

### ISSUE THREAD

**Issue by CRCinAU** [reubenhwk/radvd#99]
Lodged with Google here:
https://issuetracker.google.com/issues/119981839

Google state:
```
The device is losing its default route:

2018-11-26T22:32:21.068 - RCV <- {616 Route removed ::/0 via fe80::20d:b9ff:fe43:59a5 dev wlan0}

This is due to this packet:

2018-11-26T22:32:21.068 - RX 00:0d:b9:43:59:a5 > 3c:28:6d:0c:ca:e7 ipv6 fe80::20d:b9ff:fe43:59a5 > fe80::3e28:6dff:fe0c:cae7 icmp6 na fe80::20d:b9ff:fe43:59a5
[3C286D0CCAE7000DB94359A586DD6000000000183AFFFE80000000000000020DB9FFFE4359A5FE800000000000003E286DFFFE0CCAE788009F2140000000FE80000000000000020DB9FFFE4359A5]
```
Where the router is indicating that it's not a router any more (note the R flag is 0).

My radvd config is:
```
interface enp2s0 {
    ## (Send advertisement messages to other hosts)
    AdvSendAdvert                   on;
    AdvDefaultLifetime              9000;
    ## Use DHCPv6 for extra details...
    AdvManagedFlag                  on;
    AdvOtherConfigFlag              on;
    ## (IPv6 subnet prefix we've been assigned by our PoP)
    prefix 2407:abcd:abcd:abcd::/64 {
        AdvOnLink               on;
        AdvAutonomous           on;
    };
    ## (Advertise a DNS Server)
    RDNSS 2407:abcd:abcd:abcd::1 {};
};
```

**Comment by robbat2** [comment]
Can you please capture w/ `tcpdump -vv -ee` or wireshark on your network, showing that the capture in a more useful form?

The other thing I've seen is that sometimes a network has more than one device sending RAs, and the unexpected sender has R=0

Please also note what version of radvd is in use.

**Comment by robbat2** [comment]
tcpdump: `icmp6` is a good starting point to capture; and it will also include IPv6 neighbour discovery which can possible help some of this debugging.

**Comment by Neustradamus** [comment]
Any news?

**Comment by CRCinAU** [comment]
There was a long time ago.... Turn on ipv6 forwarding on the linux system and it will set the correct flags in the right places...

ie sysctl net.ipv6.conf.all.forwarding=1
